import assert from 'node:assert/strict';
import test from 'node:test';

import { buildAddonData, luaString, renderLuaData, toLua } from '../scripts/build-data.mjs';

test('luaString escapes characters that would break a Lua string literal', () => {
  assert.equal(luaString('A "quote" and \\ slash\nnext'), '"A \\"quote\\" and \\\\ slash\\nnext"');
});

test('toLua renders numeric recommendation keys and nested encounter fields', () => {
  const rendered = toLua({
    recommendations: {
      266: {
        mplus: { encounters: { 112526: { importString: 'CoQAAA' } } },
        raid: { encounters: { 3176: { importString: 'CoRAID' } } }
      }
    }
  });

  assert.match(rendered, /\[266\] = \{/);
  assert.match(rendered, /mplus = \{/);
  assert.match(rendered, /raid = \{/);
  assert.match(rendered, /\[112526\] = \{/);
  assert.match(rendered, /\[3176\] = \{/);
  assert.match(rendered, /importString = "CoQAAA"/);
  assert.match(rendered, /importString = "CoRAID"/);
});

test('renderLuaData creates a loadable addon data assignment', () => {
  const rendered = renderLuaData({ schemaVersion: 2, recommendations: {} });
  assert.match(rendered, /^-- Generated by scripts\/build-data\.mjs/m);
  assert.match(rendered, /QuickWoWTalentsData = \{/);
  assert.match(rendered, /schemaVersion = 2/);
});


test('buildAddonData requests Mythic+ Best Overall from keys 15 and above', async () => {
  const originalFetch = globalThis.fetch;
  const requests = [];

  globalThis.fetch = async (url) => {
    assert.equal(String(url), 'https://example.test/api/options');
    return {
      ok: true,
      json: async () => ({
        defaultRegion: 'all',
        classes: [{
          className: 'Mage',
          specs: [{ specName: 'Arcane', role: 'DPS', metrics: ['dps'] }]
        }],
        mythicPlus: {
          dungeons: [{ id: 10658, name: 'Pit of Saron' }]
        },
        raid: {
          bosses: [{ id: 3176, name: 'Test Boss' }],
          difficulties: [{ id: 4, name: 'Heroic' }]
        }
      })
    };
  };

  try {
    const payload = await buildAddonData({
      baseUrl: 'https://example.test',
      generatedAt: '2026-04-27T00:00:00.000Z',
      delayMs: 0,
      concurrency: 1,
      loadBuildPayload: async (request) => {
        requests.push(request);
        return {
          cache: { servedDayKey: '2026-04-26', capturedAt: '2026-04-26T01:00:00.000Z' },
          summary: {
            totalLogs: 100,
            distinctBuilds: 3,
            selectionBasis: request.mode === 'mplus' ? 'most-common-top-100-per-key-15-plus' : 'highest-average-top-100',
            mostCommon: {
              blizzardExportString: request.mode === 'mplus' ? 'MPLUS' : 'RAID',
              mzTalentTree: { specId: 62 },
              count: 10,
              adoptionRate: 0.1,
              averageAmount: 1000,
              bestAmount: 1200,
              apexTalent: 'Test Apex'
            }
          }
        };
      }
    });

    const mplusRequest = requests.find((request) => request.mode === 'mplus');
    assert.equal(mplusRequest.params.get('keystoneLevel'), 'overall');
    assert.equal(mplusRequest.params.get('minKeystoneLevel'), '15');

    const entry = payload.recommendations[62].mplus.encounters[10658];
    assert.equal(payload.modes.mplus.minimumKeystoneLevel, 15);
    assert.equal(payload.modes.mplus.recommendationLabel, 'Best Overall (15+)');
    assert.equal(entry.minimumKeystoneLevel, 15);
    assert.equal(entry.label, 'Arcane Mage — Pit of Saron Best Overall (15+)');
    assert.equal(entry.selectionBasis, 'most-common-top-100-per-key-15-plus');
  } finally {
    globalThis.fetch = originalFetch;
  }
});
