import assert from 'node:assert/strict';
import test from 'node:test';

import { luaString, renderLuaData, toLua } from '../scripts/build-data.mjs';

test('luaString escapes characters that would break a Lua string literal', () => {
  assert.equal(luaString('A "quote" and \\ slash\nnext'), '"A \\"quote\\" and \\\\ slash\\nnext"');
});

test('toLua renders numeric recommendation keys and nested fields', () => {
  const rendered = toLua({ recommendations: { 266: { mplusBestOverall: { importString: 'CoQAAA' } } } });
  assert.match(rendered, /\[266\] = \{/);
  assert.match(rendered, /mplusBestOverall = \{/);
  assert.match(rendered, /importString = "CoQAAA"/);
});

test('renderLuaData creates a loadable addon data assignment', () => {
  const rendered = renderLuaData({ schemaVersion: 1, recommendations: {} });
  assert.match(rendered, /^-- Generated by scripts\/build-data\.mjs/m);
  assert.match(rendered, /QuickWoWTalentsData = \{/);
  assert.match(rendered, /schemaVersion = 1/);
});
