import assert from 'node:assert/strict';
import test from 'node:test';

import * as luaParser from '../scripts/parse-addon-lua.mjs';

const { parseAddonLua } = luaParser;

const schemaThreeFixture = `-- Generated by Quick WoW Talents. Do not edit by hand.
-- Source of truth: quickwowtalents.com cache.
QuickWoWTalentsData = {
  schemaVersion = 3,
  clientInterface = 120100,
  source = "https://quickwowtalents.com",
  modes = {
    mplus = {
      dungeons = {
        { id = 10658, name = "Pit of Saron" },
        { id = 12811, name = "Magisters' Terrace" }
      }
    }
  },
  recommendations = {
    [62] = {
      mplus = { encounters = { [10658] = { importString = "CoQAAA", enabled = true, omitted = nil } } }
    }
  }
}
`;

test('parses a complete nested schema-3 generated-data fixture', () => {
  const parsed = parseAddonLua(schemaThreeFixture);

  assert.deepEqual(parsed, {
    schemaVersion: 3,
    clientInterface: 120100,
    source: 'https://quickwowtalents.com',
    modes: {
      mplus: {
        dungeons: [
          { id: 10658, name: 'Pit of Saron' },
          { id: 12811, name: "Magisters' Terrace" }
        ]
      }
    },
    recommendations: {
      62: {
        mplus: { encounters: { 10658: { importString: 'CoQAAA', enabled: true, omitted: null } } }
      }
    }
  });
});

test('decodes generated Lua string escapes without executing them', () => {
  const parsed = parseAddonLua('QuickWoWTalentsData = { text = "quote: \\"; slash: \\\\; lines: \\n; tab: \\t; carriage: \\r" }');

  assert.equal(parsed.text, 'quote: "; slash: \\; lines: \n; tab: \t; carriage: \r');
});

test('preserves numeric recommendation keys as object keys', () => {
  const parsed = parseAddonLua('QuickWoWTalentsData = { recommendations = { [62] = { importString = "A" }, [1480] = { importString = "B" } } }');

  assert.equal(Array.isArray(parsed.recommendations), false);
  assert.deepEqual(parsed.recommendations, {
    62: { importString: 'A' },
    1480: { importString: 'B' }
  });
});

test('preserves explicit Lua key kinds out of band without changing parsed values', () => {
  assert.equal(typeof luaParser.getParsedLuaKeyKind, 'function');
  const parsed = parseAddonLua(`QuickWoWTalentsData = {
    numeric = { [62] = "numeric" },
    string = { ["62"] = "string" },
    named = { value = "identifier" },
    ordered = { "implicit" }
  }`);

  assert.deepEqual(parsed, {
    numeric: { 62: 'numeric' },
    string: { 62: 'string' },
    named: { value: 'identifier' },
    ordered: ['implicit']
  });
  assert.equal(luaParser.getParsedLuaKeyKind(parsed.numeric, 62), 'number');
  assert.equal(luaParser.getParsedLuaKeyKind(parsed.string, '62'), 'string');
  assert.equal(luaParser.getParsedLuaKeyKind(parsed.named, 'value'), 'identifier');
  assert.equal(luaParser.getParsedLuaKeyKind(parsed.ordered, 1), 'implicit');
  assert.equal(luaParser.getParsedLuaKeyKind({}, 'missing'), null);
});

test('uses an object for the empty root table and arrays for nested empty tables', () => {
  const parsed = parseAddonLua('QuickWoWTalentsData = { skipped = {} }');

  assert.deepEqual(parsed, { skipped: [] });
  assert.equal(Array.isArray(parsed), false);
  assert.deepEqual(parseAddonLua('QuickWoWTalentsData = {}'), {});
});

test('rejects duplicate identifier and bracket-string table keys', () => {
  assert.throws(
    () => parseAddonLua('QuickWoWTalentsData = { source = "one", ["source"] = "two" }'),
    /duplicate key/i
  );
});

test('rejects every Lua keyword as a bare table key', () => {
  for (const keyword of [
    'and', 'break', 'do', 'else', 'elseif', 'end', 'false', 'for', 'function',
    'goto', 'if', 'in', 'local', 'nil', 'not', 'or', 'repeat', 'return', 'then',
    'true', 'until', 'while'
  ]) {
    assert.throws(
      () => parseAddonLua(`QuickWoWTalentsData = { ${keyword} = 1 }`),
      /keyword|generated Lua value|separator|expected/i,
      keyword
    );
  }
});

test('rejects executable and expression syntax', () => {
  for (const text of [
    'QuickWoWTalentsData = function() end',
    'QuickWoWTalentsData = { source = os.execute("boom") }',
    'QuickWoWTalentsData = { value = 1 + 2 }'
  ]) {
    assert.throws(() => parseAddonLua(text), /unexpected|expected|root/i);
  }
});

test('rejects invalid table separators', () => {
  assert.throws(
    () => parseAddonLua('QuickWoWTalentsData = { first = 1 second = 2 }'),
    /separator|expected/i
  );
});

test('rejects trailing executable content and noncanonical root forms', () => {
  assert.throws(
    () => parseAddonLua('QuickWoWTalentsData = {} os.execute("boom")'),
    /trailing|unexpected/i
  );
  assert.throws(
    () => parseAddonLua('OtherData = {}'),
    /QuickWoWTalentsData|root/i
  );
  assert.throws(
    () => parseAddonLua('QuickWoWTalentsData = {}\nQuickWoWTalentsData = {}'),
    /trailing|unexpected/i
  );
  for (const text of [
    'local QuickWoWTalentsData = {}',
    'QuickWoWTalentsData.value = {}',
    'QuickWoWTalentsData = DataAlias',
    'DataAlias = QuickWoWTalentsData'
  ]) {
    assert.throws(() => parseAddonLua(text), /QuickWoWTalentsData|root|table|unexpected/i);
  }
});
